name: Create pull request from development to staging
on:
  push:
    branches:
      - development
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: staging
          base: development
          title: "development -> staging"
          body: "development -> staging"
